name: Keep Render App Awake

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          curl -s https://https://tony-p9k2.onrender.com/dev/null
          echo "Ping successful!"
